[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
universal_liquidity_pool_soonv1 = "GndtcpvZJN6ybuNZJQsRGbBCAX32cHHYev4aJjbDrzLY"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://rpc.devnet.soo.network/rpc"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
